### ISSUE TITLE
Deactivate/Delete Program

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#141]
When I do this, the screen goes into a zombie state. Should we either blank the selector or render details for the selection in the dropdown - in this case RCT Math:

![image](https://cloud.githubusercontent.com/assets/465382/23019931/9b72ea42-f46a-11e6-81db-b3693b0b870f.png)

**Comment by meghaklp** [comment]
We should probably not allow deactivate/ delete if the program has active assessments under it.

**Comment by subhaklp** [comment]
do you want me to show a pop up if delete is not allowed? I think that's better than graying out the button..because then people will go "Why?"

**Comment by subhaklp** [comment]
@meghaklp i don't see it go into a zombie state at least with the latest codebase. It actually displays the next program in the dropdown..you see any errors in the console?

**Comment by subhaklp** [comment]
I fixed this by disabling the buttons. But haven't added any tooltip or message as to why its disabled. This is because tooltips or popovers don't appear on disabled buttons. So not sure how best to communicate this? If disabling is okay as a solution, then we can close this. @meghaklp please comment.

**Comment by meghaklp** [comment]
Disabling is okay. Let's close this for now.
