### ISSUE TITLE
Generic Nav tree behaviour - one node open only

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#203]
Can we modify the nav tree behaviour:

Among peer nodes only one node can be open at any time. So if a user clicks on a new node, the open peer nodes are forcefully closed.

For Example, 
Only 1 district drop down can be fully expanded to 1 school at a time
If I click on another school in the same cluster, the previously open school should close.

It may help close some of the issues.

**Comment by subhaklp** [comment]
@meghaklp working on figuring out why multiple nodes being open should cause these issues. If this is a UX request, then we'll implement it right away. But if this is a workaround to avoiding some of the bugs we're having the nav tree, I'd rather get to the bottom of it rather than dance around it. Please clarify.

**Comment by meghaklp** [comment]
@subhaklp From a UX perspective, if the nav tree has more expanded nodes it becomes clunkier to operate - more scrolling, more seeking, etc 

But if you want to get to the bottom of the issue first and then make UX fix, I'm fine with that approach.
